name: Build Docker image

on: [pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build container image
        uses: docker/build-push-action@v4
        with:
          context: .
